### ISSUE TITLE
[Android Termux] gotop crashes on startup

### ISSUE THREAD

**Issue by joeky888** [cjbassi/gotop#65]
Termux app https://play.google.com/store/apps/details?id=com.termux

I tried x64 Android and aarch64 Android, got same error.

Here is the aarch64 Android sysinfo:

```yaml
$ lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  4
Socket(s):           2
Vendor ID:           Qualcomm
Model:               4
Model name:          Kryo V2
Stepping:            0xa
CPU max MHz:         1804.8000
CPU min MHz:         633.6000
BogoMIPS:            38.40
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32

$ neofetch
OS: Android 8.1.0 aarch64 
Host: asus ASUS_X00TDB 
Kernel: 4.4.78-perf+ 
Uptime: secs 
Packages: 130 (dpkg), 1 (pkg) 
Shell: bash 4.4.23 
CPU: Qualcomm SDM636 (8) @ 1.612GHz 
Memory: 2236MiB / 5744MiB
```

```yaml
$ gotop
Error caught. Exiting program.

Issue with CPU percentages.

Diagnostics:
self.Count: 6
gopsutil.Counts(): 6
len(percents): 0
percents: []
self.interval: 1s

panic: 1

goroutine 21 [running]:
github.com/cjbassi/gotop/src/utils.Error(0x9e7edd2bc, 0xf, 0x4000362000, 0x52)
        /data/data/com.termux/files/home/go/src/github.com/cjbassi/gotop/src/utils/utils.go:63 +0x1a0
github.com/cjbassi/gotop/src/widgets.(*CPU).update.func2(0x4000150000)
        /data/data/com.termux/files/home/go/src/github.com/cjbassi/gotop/src/widgets/cpu.go:78 +0x490
created by github.com/cjbassi/gotop/src/widgets.(*CPU).update
        /data/data/com.termux/files/home/go/src/github.com/cjbassi/gotop/src/widgets/cpu.go:74 +0x4c
```

I am counting on gotop right now,

because gtop, vtop and glances, none of these works on my phone lol.
